<template>
  <div class="home">
    <el-button icon="fa fa-edit">编辑</el-button>
    <i class="fa fa-audio-description"></i>
    <p>首wwwwwwwwwwwww页</p>
    <p>首页2222222/p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
  </div>
</template>
<script>
  export default {
    mounted () {
//      this.$store.commit('setBreadlist', [{path: '/home', meta: {title: '首页'}}]);
    }
  }
</script>
<style lang="scss" scoped>
  .home{

  }
</style>
